default:
    project_base: "/projects/nhl_meta_analysis_scratch/gambl/results_local/"
    repo_base: "/projects/rmorin/projects/gambl-repos/gambl-rmorin/"
    derived_and_curated: "icgc_dart/derived_and_curated_metadata/"
    database_name: "gambl_test"

    results:
        tidy_expression_file: "/projects/rmorin/projects/gambl-repos/gambl-rmorin/results/icgc_dart/DESeq2-0.0_salmon-1.0/mrna--gambl-icgc-all/vst-matrix-Hugo_Symbol_tidy.tsv"
        ex_matrix_file: "/projects/rmorin/projects/gambl-repos/gambl-rmorin/results/icgc_dart/DESeq2-0.0_salmon-1.0/mrna--gambl-icgc-all/vst-matrix-Hugo_Symbol.tsv.gz"

#results from every combination of each of these will be included in the database
    unix_groups: "gambl,icgc_dart"
    genome_builds: "grch37,hg38,hs37d5"

    analyses:
        matched:
            copy_number_tool: "battenberg"
            ssm_tool: "slms-3"
        unmatched:
            copy_number_tool: "controlfreec"
            ssm_tool: "slms-3"

#tables that likely need to be populated sequentially or outside of R due to their size
    results_tables:
        ssm: "maf_slms3_hg19_icgc"
        copy_number: "seg_battenberg_hg19"

    results_filatfiles:
        ssm: "results/icgc_dart/slms-3_vcf2maf_current/level_3/final_merged_gambL-icgc_grch37.maf"

    tables:
        biopsies: "biopsy_metadata"
        samples: "sample_metadata"
        outcomes: "outcome_metadata"
        derived: "derived_data"

    table_flatfiles:
        biopsies: "data/metadata/gambl_biopsy_metadata.tsv"
        samples: "data/metadata/gambl_samples_available.tsv"
        outcomes: "data/metadata/private_metadata/gambl_all_outcomes.tsv"
        derived: "data/metadata/gambl_sample_results.tsv"
